### PR TITLE
re #251 - Removed (balance) from Louisville/Jefferson County

### PR DESCRIPTION
**Pull request by stepps00**

### CODE REVIEW

**Comment by nvkelso** [comment]
I'm assuming this is also true:

```
Don't modify original qs:loc and qs:loc_alt properties.
```

**Comment by nvkelso** [comment]
Suggest:

`wof:name` to **Louisville**
`wof:label` to **Louisville Metro**

See: 

* https://en.wikipedia.org/wiki/Government_of_Louisville,_Kentucky

**Comment by stepps00** [comment]
Changed:
* `wof:name` to **Louisville**
* `wof:label` to **Louisville Metro**

**Comment by nvkelso** [comment]
LGTM, over to @thisisaaronland to merge.

**Pull request merged**
