### PR TITLE
re #251 - Removed 'city (balance)' from Indianapolis

### PR DESCRIPTION
**Pull request by stepps00**

### CODE REVIEW

**Comment by nvkelso** [comment]
```
Don't modify original qs:loc and qs:loc_alt properties.
```

But do modify, `wof:name`.

**Comment by nvkelso** [comment]
Nothing to see here? The `qs` stuff was reverted, but looks like the `wof:name` was already good as **Indianapolis**, so just close this issue?

**Comment by trescube** [comment]
Didn't I fix this with https://github.com/whosonfirst/whosonfirst-data/pull/260?

**Comment by stepps00** [comment]
`qs` field edits were reverted, so no changes were made to this record. Closing the issue because there are no conflicts with the base branch.

**Pull request closed without merging**
