### PR TITLE
Mitte typo

### PR DESCRIPTION
**Pull request by missinglink**
re: https://whosonfirst.mapzen.com/spelunker/id/420784293

Correct spelling is `Mitte` not `MItte`

https://en.wikipedia.org/wiki/Mitte_(locality)

### CODE REVIEW

**Comment by missinglink** [comment]
agh, it seems this Feature is a Point, not a Polygon, that's probably why..

**Comment by nvkelso** [comment]
(Unrelated to spelling change...)

Wait, where did the polygon geometry go (it just has a [point geom](https://raw.githubusercontent.com/whosonfirst/whosonfirst-data/542913b5e7ac46d7328867e1f67c799189aab9fb/data/420/784/293/420784293.geojson) now)? Seems like it's gone for all the Berlin neighbourhoods? And no history before @thisisaaronland commit https://github.com/whosonfirst/whosonfirst-data/commits/master/data/420/784/293/420784293.geojson importing Nat's curation work? Huh?

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/whosonfirst-data/blame/master/data/420/784/293/420784293.geojson

```
grep MItte wof-neighbourhood-20151211-pts-nat.geojson 
{ "type": "Feature", "properties": { "WOF_NAME": "MItte", "MZ_MIN_ZOO": 11.0, "MZ_MAX_ZOO": 17.0, "MZ_IS_LAND": null, "MZ_IS_FUNK": null, "MZ_IS_OFFI": null, "MZ_IS_HARD": null, "TIER_LOCAL": null, "TIER_METRO": 1.0, "WOF_S_NEW": null, "WOF_S_OLD": null, "NAME_ALTS": null, "WOF_ID": null, "WOF_COUNTR": null, "WOF_LANG": null, "WOE_ADM0": null, "WOE_ADM1": null, "WOE_ADM2": null, "WOF_LOCAL": null, "WOF_LOC_ID": null, "WOE_LOCALI": null, "LBL_LAT": null, "LBL_LNG": null, "O_WOF_NAME": null, "O_MZ_MIN_Z": null, "O_MZ_MAX_Z": null, "O_MZ_IS_LA": null, "O_MZ_IS_FU": null, "ISO_COUNT": null, "LBL_LATITU": null, "LBL_LONGIT": null, "NOTE": null, "weblink": null }, "geometry": { "type": "Point", "coordinates": [ 13.39087980121602, 52.515859067461122 ] } },
```

**Comment by missinglink** [comment]
I'd love the polygons if you have 'em, I assumed it was a placeholder until we get some.
Did they used to be in there?

**Comment by nvkelso** [comment]
Oh, I see. `Mitte` was missing from Quattroshapes (and from WOF) and Nat added it as a point geometry only suitable for labeling during his 1st contract. When I spot check other Berlin neighbourhoods that are known to be in Quattroshapes they do have polygon geometry in WOF. The few I spot checked before must have also been missing from QS. 

Point geoms are totally legit and expected, but might be worthy of a debug view in BI or the Spelunker?

QS map view:

screen shot 2016-06-08 at 09 09 19

QS data table view:

screen shot 2016-06-08 at 09 12 43

**Comment by nvkelso** [comment]
Looks like @missinglink's commit just needs to be exportified (to update the date) and then ready to merge?

**Comment by thisisaaronland** [comment]
Define "debug view". The whole thing is basically a big debug view ;-)

**Comment by missinglink** [comment]
FYI: also affects https://whosonfirst.mapzen.com/spelunker/id/420784305

**Pull request merged**
