### PR TITLE
Linked countries, dependencies, disputes to empires

### LINKED ISSUE #4: Link up countries, dependencies, disputes to empires
A couple dozen countries, dependencies, & disputed areas should be linked up to parent empires.

Document research here and apply data changes.

### PR DESCRIPTION
**Pull request by stepps00**
Fixes #4 

For the list of countries, dependencies, and disputes in the issue, the following fields were updated in this PR:
* `wof:belongsto`
* `wof:belongs` (if applicable)
* `wof:hierarchy`
* `wof:lastmodified` (through Exportify tool)

If the record already had a `wof:belongs` field with values, the empire ID was added to the field. If the record did not have a `wof:belongs` field, no values were added.

Only one record (the [Baykonur lease in Qyzylorda](https://whosonfirst.mapzen.com/spelunker/id/85681265/#8/45.980/63.384)) was not updated. This record was not updated because its parent ([Russia](https://whosonfirst.mapzen.com/spelunker/id/85632685/#2/69.6/0.0)) does not have an empire record in WOF. Is the Baykonur lease in Qyzylorda record acceptable as-is or should we create a new Russian empire record for its hierarchy?

### CODE REVIEW

**Comment by nvkelso** [comment]
@stepps00 Create a new Russian empire for Baykonur.

**Comment by nvkelso** [comment]
There are 58 of 59 requested changes. After fixing `Baykonur` we'll achieve 59. I spot checked around 30% of these, they look good.

**Comment by stepps00** [comment]
[Most recent commit](https://github.com/whosonfirst/whosonfirst-data/pull/330/commits/c6adafc7abe79cb322f1e90cd0056f975606ef29) includes new `empire` record for Russia and updates to two existing records.

* Created new `empire` record for Russia using a new Brooklyn Integer file name/path. Copied existing `empire` record, but changed `id`, `wof:id`, and `wof:name` fields.
* Updated records for Baykonur and Russia to include new `empire` id in the `wof:hirarchy` and `wof:belongsto` fields.
* Updated `lastmodified` field.

**Comment by nvkelso** [comment]
LGTM

**Comment by thisisaaronland** [comment]
A few comments, in no particular order:

* Apparently this can't merge cleanly anymore...
* What no geometries for the Empires ;-)
* belongsto IDs are being encoded as strings but that's not directly related to this issue

I will look to merge shortly.

**Comment by nvkelso** [comment]
For a rainy day, empire geoms: https://github.com/whosonfirst/whosonfirst-data/issues/335.

**Comment by stepps00** [comment]
Conflict resolved! `lastmodified` field conflict was taken care of for 26 conflicting records - branch should be OK to merge now.

**Pull request merged**
